#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd "$SCRIPT_DIR"/src
sudo env "GOPATH=$GOPATH" $GOPATH/bin/qtdeploy -docker build windows_64_static
sudo chown -R $USER "$SCRIPT_DIR"
mv deploy "$SCRIPT_DIR"
rmdir windows
go mod tidy
cd "$SCRIPT_DIR"
